# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 17:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171003_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Employee')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('users.employee',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='eligible_for_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=15, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='physical_working_location',
            field=models.CharField(default='', max_length=100, verbose_name='Normal Physical Working Location'),
            preserve_default=False,
        ),
    ]
