# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171003_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, verbose_name='Emergency Contact Number'),
        ),
    ]
