# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171003_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Employee'),
            preserve_default=False,
        ),
    ]
