# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171003_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='supervisor',
            new_name='supervisor_id',
        ),
    ]
