# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171004_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='Supervisor'),
        ),
    ]
