# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171004_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor_id',
        ),
    ]
