# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantAward',
            fields=[
                ('grant_award_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Grant Award ID')),
                ('grant_award_description', models.CharField(blank=True, max_length=100, verbose_name='Grant Award Description')),
                ('grant_award_start_date', models.DateField()),
                ('grant_award_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GrantAwardTask',
            fields=[
                ('grant_award_task_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Grant Award Task ID')),
                ('grant_award_task_description', models.CharField(blank=True, max_length=100, verbose_name='Grant Award Task Description')),
                ('grant_award_task_start_date', models.DateField()),
                ('grant_award_task_end_date', models.DateField()),
                ('grant_award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.GrantAward')),
            ],
        ),
    ]
