# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0001_initial'),
        ('payperiods', '0001_initial'),
        ('users', '0005_auto_20171003_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Hours spent on this activity')),
                ('activity_category', models.CharField(choices=[('regular', 'Regular Time'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('personal', 'Personal'), ('bereavement', 'Bereavement'), ('holiday', 'Holiday'), ('jury_duty', 'Jury Duty'), ('workers_comp', 'Workers Compensation'), ('union_duties', 'Union Duties'), ('training_conf_sem', 'Training, Conference, or Seminar'), ('other', 'Other')], default='regular', max_length=30, verbose_name='Activity Category')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('grant_award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.GrantAward', verbose_name='Grant Award for this activity.')),
                ('grant_award_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.GrantAwardTask')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unsubmitted', 'Not Yet Submitted'), ('submitted', 'Submitted to Supervisor'), ('rejected_sup', 'Rejected by Supervisor - Awaiting Revision'), ('approved', 'Approved by Supervisor - Awaiting HR Review'), ('rejected_hr', 'Rejected by HR - Awaiting Revision'), ('processed_hr', 'Processed by HR'), ('paid', 'Paid')], default='unsubmitted', max_length=30, verbose_name='Timesheet Status')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payperiods.PayPeriod')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.Timesheet'),
        ),
    ]
